version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install zip -y
      - ls -la
      - uname -a
      - zip start.zip start.py
      - aws lambda update-function-code --function-name start --zip-file fileb://start.zip --publish