version: 0.2

phases:
  installl:
    - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lablocat --output-template-file NewSamTemplate.yaml
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - HelloWorld.zip