version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - aws cloudformation package --template-file github.yaml --s3-bucket lablocat --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml