version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install zip -y
      - ls -la
      - zip github.zip Helloword.py
      - aws lambda update-function-code --function-name github --zip-file fileb://github.zip --publish