version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install zip -y
      - ls -la
      - zip -r numpy.zip .
      - aws lambda update-function-code --function-name numpy_example --zip-file fileb://numpy.zip --publish